/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EmployeeId = IDL.Nat;
export const GoalId = IDL.Nat;
export const GoalStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
  'failed' : IDL.Null,
});
export const Time = IDL.Int;
export const Goal = IDL.Record({
  'id' : GoalId,
  'status' : GoalStatus,
  'title' : IDL.Text,
  'endDate' : Time,
  'description' : IDL.Text,
  'progress' : IDL.Nat,
  'startDate' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TaskId = IDL.Nat;
export const TaskStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'done' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const OnboardingTask = IDL.Record({
  'id' : TaskId,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'dueDate' : Time,
  'description' : IDL.Text,
  'links' : IDL.Text,
  'notes' : IDL.Text,
});
export const ExternalEmployeeId = IDL.Text;
export const CreateEmployeeProfileArgs = IDL.Record({
  'manager' : IDL.Text,
  'externalEmployeeId' : IDL.Opt(ExternalEmployeeId),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'jobTitle' : IDL.Text,
  'department' : IDL.Text,
  'principalId' : IDL.Opt(IDL.Principal),
  'startDate' : Time,
});
export const CycleId = IDL.Nat;
export const CycleStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'draft' : IDL.Null,
});
export const PerformanceReviewCycle = IDL.Record({
  'id' : CycleId,
  'status' : CycleStatus,
  'title' : IDL.Text,
  'endDate' : Time,
  'startDate' : Time,
});
export const ReviewId = IDL.Nat;
export const AppraisalDetails = IDL.Record({
  'employeeName' : IDL.Text,
  'teamwork' : IDL.Text,
  'overallRatingPercent' : IDL.Nat,
  'createdAt' : Time,
  'timeliness' : IDL.Text,
  'feedback' : IDL.Vec(IDL.Text),
  'qualityOfWork' : IDL.Text,
  'appraisalType' : IDL.Text,
  'communicationSkills' : IDL.Text,
  'appraisalPeriod' : IDL.Text,
  'jobTitle' : IDL.Text,
  'employeeId' : EmployeeId,
  'incrementPercent' : IDL.Nat,
  'grade' : IDL.Text,
  'workCompletionPercent' : IDL.Nat,
  'criteria' : IDL.Vec(IDL.Text),
  'department' : IDL.Text,
  'reasonForIncrement' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'employeeId' : IDL.Opt(EmployeeId),
});
export const EmploymentStatus = IDL.Variant({
  'active' : IDL.Null,
  'terminated' : IDL.Null,
});
export const EmployeeProfile = IDL.Record({
  'id' : EmployeeId,
  'status' : EmploymentStatus,
  'manager' : IDL.Text,
  'externalEmployeeId' : IDL.Opt(ExternalEmployeeId),
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'performanceCycleId' : IDL.Opt(IDL.Nat),
  'email' : IDL.Text,
  'jobTitle' : IDL.Text,
  'department' : IDL.Text,
  'onboardingPlanId' : IDL.Opt(IDL.Nat),
  'principalId' : IDL.Opt(IDL.Principal),
  'startDate' : Time,
});
export const ReviewStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const Review = IDL.Record({
  'id' : ReviewId,
  'hrReview' : IDL.Text,
  'status' : ReviewStatus,
  'managerReview' : IDL.Text,
  'selfReview' : IDL.Text,
  'employeeId' : EmployeeId,
  'cycleId' : CycleId,
});
export const OnboardingResponse = IDL.Record({
  'response' : IDL.Text,
  'timestamp' : Time,
  'questionId' : IDL.Nat,
});
export const QuestionnaireResponse = IDL.Record({
  'responses' : IDL.Vec(OnboardingResponse),
  'submittedAt' : Time,
  'submittedBy' : IDL.Principal,
  'employeeId' : EmployeeId,
});
export const SearchResult = IDL.Variant({
  'review' : IDL.Record({ 'review' : Review, 'employeeId' : EmployeeId }),
  'onboardingTask' : IDL.Record({
    'task' : OnboardingTask,
    'employeeId' : EmployeeId,
  }),
  'goal' : IDL.Record({ 'goal' : Goal, 'employeeId' : EmployeeId }),
  'questionnaireResponse' : IDL.Record({
    'employeeId' : EmployeeId,
    'response' : QuestionnaireResponse,
  }),
  'employee' : EmployeeProfile,
  'appraisal' : AppraisalDetails,
});
export const UpdateEmployeeProfileArgs = IDL.Record({
  'status' : IDL.Opt(EmploymentStatus),
  'manager' : IDL.Opt(IDL.Text),
  'externalEmployeeId' : IDL.Opt(ExternalEmployeeId),
  'name' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'jobTitle' : IDL.Opt(IDL.Text),
  'department' : IDL.Opt(IDL.Text),
  'principalId' : IDL.Opt(IDL.Principal),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGoals' : IDL.Func([EmployeeId, IDL.Vec(Goal)], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignOnboardingTasks' : IDL.Func(
      [EmployeeId, IDL.Vec(OnboardingTask)],
      [IDL.Bool],
      [],
    ),
  'createEmployee' : IDL.Func(
      [CreateEmployeeProfileArgs],
      [IDL.Opt(EmployeeId)],
      [],
    ),
  'createPerformanceCycle' : IDL.Func([PerformanceReviewCycle], [CycleId], []),
  'createReview' : IDL.Func([EmployeeId, CycleId], [ReviewId], []),
  'ensureUserProfile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Principal], []),
  'getAllPerformanceCycles' : IDL.Func(
      [],
      [IDL.Vec(PerformanceReviewCycle)],
      ['query'],
    ),
  'getAppraisalDetails' : IDL.Func(
      [EmployeeId],
      [IDL.Opt(AppraisalDetails)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployee' : IDL.Func([EmployeeId], [IDL.Opt(EmployeeProfile)], ['query']),
  'getEmployeeGoals' : IDL.Func(
      [EmployeeId],
      [IDL.Opt(IDL.Vec(Goal))],
      ['query'],
    ),
  'getEmployeeReviews' : IDL.Func(
      [EmployeeId],
      [IDL.Opt(IDL.Vec(Review))],
      ['query'],
    ),
  'getMyEmployeeId' : IDL.Func([], [IDL.Opt(EmployeeId)], []),
  'getOnboardingQuestions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getOnboardingTasks' : IDL.Func(
      [EmployeeId],
      [IDL.Opt(IDL.Vec(OnboardingTask))],
      ['query'],
    ),
  'getPerformanceCycle' : IDL.Func(
      [CycleId],
      [IDL.Opt(PerformanceReviewCycle)],
      ['query'],
    ),
  'getQuestionnaireResponses' : IDL.Func(
      [EmployeeId],
      [IDL.Vec(QuestionnaireResponse)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'globalSearch' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAppraisalDetails' : IDL.Func([AppraisalDetails], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchAppraisalDetails' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AppraisalDetails)],
      ['query'],
    ),
  'searchEmployees' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(EmployeeProfile)],
      ['query'],
    ),
  'submitHRReview' : IDL.Func([EmployeeId, ReviewId, IDL.Text], [IDL.Bool], []),
  'submitManagerReview' : IDL.Func(
      [EmployeeId, ReviewId, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'submitQuestionnaireResponses' : IDL.Func(
      [EmployeeId, IDL.Vec(OnboardingResponse)],
      [],
      [],
    ),
  'submitSelfReview' : IDL.Func(
      [EmployeeId, ReviewId, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateEmployee' : IDL.Func(
      [EmployeeId, UpdateEmployeeProfileArgs],
      [IDL.Bool],
      [],
    ),
  'updateGoalProgress' : IDL.Func(
      [EmployeeId, GoalId, IDL.Nat, GoalStatus],
      [IDL.Bool],
      [],
    ),
  'updateOnboardingTaskStatus' : IDL.Func(
      [EmployeeId, TaskId, TaskStatus],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EmployeeId = IDL.Nat;
  const GoalId = IDL.Nat;
  const GoalStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Goal = IDL.Record({
    'id' : GoalId,
    'status' : GoalStatus,
    'title' : IDL.Text,
    'endDate' : Time,
    'description' : IDL.Text,
    'progress' : IDL.Nat,
    'startDate' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TaskId = IDL.Nat;
  const TaskStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'done' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const OnboardingTask = IDL.Record({
    'id' : TaskId,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'dueDate' : Time,
    'description' : IDL.Text,
    'links' : IDL.Text,
    'notes' : IDL.Text,
  });
  const ExternalEmployeeId = IDL.Text;
  const CreateEmployeeProfileArgs = IDL.Record({
    'manager' : IDL.Text,
    'externalEmployeeId' : IDL.Opt(ExternalEmployeeId),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'jobTitle' : IDL.Text,
    'department' : IDL.Text,
    'principalId' : IDL.Opt(IDL.Principal),
    'startDate' : Time,
  });
  const CycleId = IDL.Nat;
  const CycleStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'draft' : IDL.Null,
  });
  const PerformanceReviewCycle = IDL.Record({
    'id' : CycleId,
    'status' : CycleStatus,
    'title' : IDL.Text,
    'endDate' : Time,
    'startDate' : Time,
  });
  const ReviewId = IDL.Nat;
  const AppraisalDetails = IDL.Record({
    'employeeName' : IDL.Text,
    'teamwork' : IDL.Text,
    'overallRatingPercent' : IDL.Nat,
    'createdAt' : Time,
    'timeliness' : IDL.Text,
    'feedback' : IDL.Vec(IDL.Text),
    'qualityOfWork' : IDL.Text,
    'appraisalType' : IDL.Text,
    'communicationSkills' : IDL.Text,
    'appraisalPeriod' : IDL.Text,
    'jobTitle' : IDL.Text,
    'employeeId' : EmployeeId,
    'incrementPercent' : IDL.Nat,
    'grade' : IDL.Text,
    'workCompletionPercent' : IDL.Nat,
    'criteria' : IDL.Vec(IDL.Text),
    'department' : IDL.Text,
    'reasonForIncrement' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'employeeId' : IDL.Opt(EmployeeId),
  });
  const EmploymentStatus = IDL.Variant({
    'active' : IDL.Null,
    'terminated' : IDL.Null,
  });
  const EmployeeProfile = IDL.Record({
    'id' : EmployeeId,
    'status' : EmploymentStatus,
    'manager' : IDL.Text,
    'externalEmployeeId' : IDL.Opt(ExternalEmployeeId),
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'performanceCycleId' : IDL.Opt(IDL.Nat),
    'email' : IDL.Text,
    'jobTitle' : IDL.Text,
    'department' : IDL.Text,
    'onboardingPlanId' : IDL.Opt(IDL.Nat),
    'principalId' : IDL.Opt(IDL.Principal),
    'startDate' : Time,
  });
  const ReviewStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Review = IDL.Record({
    'id' : ReviewId,
    'hrReview' : IDL.Text,
    'status' : ReviewStatus,
    'managerReview' : IDL.Text,
    'selfReview' : IDL.Text,
    'employeeId' : EmployeeId,
    'cycleId' : CycleId,
  });
  const OnboardingResponse = IDL.Record({
    'response' : IDL.Text,
    'timestamp' : Time,
    'questionId' : IDL.Nat,
  });
  const QuestionnaireResponse = IDL.Record({
    'responses' : IDL.Vec(OnboardingResponse),
    'submittedAt' : Time,
    'submittedBy' : IDL.Principal,
    'employeeId' : EmployeeId,
  });
  const SearchResult = IDL.Variant({
    'review' : IDL.Record({ 'review' : Review, 'employeeId' : EmployeeId }),
    'onboardingTask' : IDL.Record({
      'task' : OnboardingTask,
      'employeeId' : EmployeeId,
    }),
    'goal' : IDL.Record({ 'goal' : Goal, 'employeeId' : EmployeeId }),
    'questionnaireResponse' : IDL.Record({
      'employeeId' : EmployeeId,
      'response' : QuestionnaireResponse,
    }),
    'employee' : EmployeeProfile,
    'appraisal' : AppraisalDetails,
  });
  const UpdateEmployeeProfileArgs = IDL.Record({
    'status' : IDL.Opt(EmploymentStatus),
    'manager' : IDL.Opt(IDL.Text),
    'externalEmployeeId' : IDL.Opt(ExternalEmployeeId),
    'name' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'jobTitle' : IDL.Opt(IDL.Text),
    'department' : IDL.Opt(IDL.Text),
    'principalId' : IDL.Opt(IDL.Principal),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGoals' : IDL.Func([EmployeeId, IDL.Vec(Goal)], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignOnboardingTasks' : IDL.Func(
        [EmployeeId, IDL.Vec(OnboardingTask)],
        [IDL.Bool],
        [],
      ),
    'createEmployee' : IDL.Func(
        [CreateEmployeeProfileArgs],
        [IDL.Opt(EmployeeId)],
        [],
      ),
    'createPerformanceCycle' : IDL.Func(
        [PerformanceReviewCycle],
        [CycleId],
        [],
      ),
    'createReview' : IDL.Func([EmployeeId, CycleId], [ReviewId], []),
    'ensureUserProfile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Principal], []),
    'getAllPerformanceCycles' : IDL.Func(
        [],
        [IDL.Vec(PerformanceReviewCycle)],
        ['query'],
      ),
    'getAppraisalDetails' : IDL.Func(
        [EmployeeId],
        [IDL.Opt(AppraisalDetails)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployee' : IDL.Func(
        [EmployeeId],
        [IDL.Opt(EmployeeProfile)],
        ['query'],
      ),
    'getEmployeeGoals' : IDL.Func(
        [EmployeeId],
        [IDL.Opt(IDL.Vec(Goal))],
        ['query'],
      ),
    'getEmployeeReviews' : IDL.Func(
        [EmployeeId],
        [IDL.Opt(IDL.Vec(Review))],
        ['query'],
      ),
    'getMyEmployeeId' : IDL.Func([], [IDL.Opt(EmployeeId)], []),
    'getOnboardingQuestions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getOnboardingTasks' : IDL.Func(
        [EmployeeId],
        [IDL.Opt(IDL.Vec(OnboardingTask))],
        ['query'],
      ),
    'getPerformanceCycle' : IDL.Func(
        [CycleId],
        [IDL.Opt(PerformanceReviewCycle)],
        ['query'],
      ),
    'getQuestionnaireResponses' : IDL.Func(
        [EmployeeId],
        [IDL.Vec(QuestionnaireResponse)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'globalSearch' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAppraisalDetails' : IDL.Func([AppraisalDetails], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchAppraisalDetails' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AppraisalDetails)],
        ['query'],
      ),
    'searchEmployees' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EmployeeProfile)],
        ['query'],
      ),
    'submitHRReview' : IDL.Func(
        [EmployeeId, ReviewId, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'submitManagerReview' : IDL.Func(
        [EmployeeId, ReviewId, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'submitQuestionnaireResponses' : IDL.Func(
        [EmployeeId, IDL.Vec(OnboardingResponse)],
        [],
        [],
      ),
    'submitSelfReview' : IDL.Func(
        [EmployeeId, ReviewId, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateEmployee' : IDL.Func(
        [EmployeeId, UpdateEmployeeProfileArgs],
        [IDL.Bool],
        [],
      ),
    'updateGoalProgress' : IDL.Func(
        [EmployeeId, GoalId, IDL.Nat, GoalStatus],
        [IDL.Bool],
        [],
      ),
    'updateOnboardingTaskStatus' : IDL.Func(
        [EmployeeId, TaskId, TaskStatus],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };