/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateEmployeeProfileArgs {
  'manager' : string,
  'name' : string,
  'email' : string,
  'jobTitle' : string,
  'department' : string,
  'principalId' : [] | [Principal],
  'startDate' : Time,
}
export type CycleId = bigint;
export type CycleStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'draft' : null };
export type EmployeeId = bigint;
export interface EmployeeProfile {
  'id' : EmployeeId,
  'status' : EmploymentStatus,
  'manager' : string,
  'name' : string,
  'createdBy' : Principal,
  'performanceCycleId' : [] | [bigint],
  'email' : string,
  'jobTitle' : string,
  'department' : string,
  'onboardingPlanId' : [] | [bigint],
  'principalId' : [] | [Principal],
  'startDate' : Time,
}
export type EmploymentStatus = { 'active' : null } |
  { 'terminated' : null };
export interface Goal {
  'id' : GoalId,
  'status' : GoalStatus,
  'title' : string,
  'endDate' : Time,
  'description' : string,
  'progress' : bigint,
  'startDate' : Time,
}
export type GoalId = bigint;
export type GoalStatus = { 'notStarted' : null } |
  { 'completed' : null } |
  { 'inProgress' : null } |
  { 'failed' : null };
export interface OnboardingTask {
  'id' : TaskId,
  'status' : TaskStatus,
  'title' : string,
  'dueDate' : Time,
  'description' : string,
  'links' : string,
  'notes' : string,
}
export interface PerformanceReviewCycle {
  'id' : CycleId,
  'status' : CycleStatus,
  'title' : string,
  'endDate' : Time,
  'startDate' : Time,
}
export interface Review {
  'id' : ReviewId,
  'hrReview' : string,
  'status' : ReviewStatus,
  'managerReview' : string,
  'selfReview' : string,
  'employeeId' : EmployeeId,
  'cycleId' : CycleId,
}
export type ReviewId = bigint;
export type ReviewStatus = { 'pending' : null } |
  { 'completed' : null };
export type TaskId = bigint;
export type TaskStatus = { 'notStarted' : null } |
  { 'done' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface UpdateEmployeeProfileArgs {
  'status' : [] | [EmploymentStatus],
  'manager' : [] | [string],
  'name' : [] | [string],
  'email' : [] | [string],
  'jobTitle' : [] | [string],
  'department' : [] | [string],
  'principalId' : [] | [Principal],
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'employeeId' : [] | [EmployeeId],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGoals' : ActorMethod<[EmployeeId, Array<Goal>], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignOnboardingTasks' : ActorMethod<
    [EmployeeId, Array<OnboardingTask>],
    boolean
  >,
  'createEmployee' : ActorMethod<
    [CreateEmployeeProfileArgs],
    [] | [EmployeeId]
  >,
  'createPerformanceCycle' : ActorMethod<[PerformanceReviewCycle], CycleId>,
  'createReview' : ActorMethod<[EmployeeId, CycleId], ReviewId>,
  'getAllPerformanceCycles' : ActorMethod<[], Array<PerformanceReviewCycle>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmployee' : ActorMethod<[EmployeeId], [] | [EmployeeProfile]>,
  'getEmployeeGoals' : ActorMethod<[EmployeeId], [] | [Array<Goal>]>,
  'getEmployeeReviews' : ActorMethod<[EmployeeId], [] | [Array<Review>]>,
  'getMyEmployeeId' : ActorMethod<[], [] | [EmployeeId]>,
  'getOnboardingTasks' : ActorMethod<
    [EmployeeId],
    [] | [Array<OnboardingTask>]
  >,
  'getPerformanceCycle' : ActorMethod<[CycleId], [] | [PerformanceReviewCycle]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchEmployees' : ActorMethod<[string], Array<EmployeeProfile>>,
  'submitHRReview' : ActorMethod<[EmployeeId, ReviewId, string], boolean>,
  'submitManagerReview' : ActorMethod<[EmployeeId, ReviewId, string], boolean>,
  'submitSelfReview' : ActorMethod<[EmployeeId, ReviewId, string], boolean>,
  'updateEmployee' : ActorMethod<
    [EmployeeId, UpdateEmployeeProfileArgs],
    boolean
  >,
  'updateGoalProgress' : ActorMethod<
    [EmployeeId, GoalId, bigint, GoalStatus],
    boolean
  >,
  'updateOnboardingTaskStatus' : ActorMethod<
    [EmployeeId, TaskId, TaskStatus],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];