/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Goal {
    id: GoalId;
    status: GoalStatus;
    title: string;
    endDate: Time;
    description: string;
    progress: bigint;
    startDate: Time;
}
export interface UserProfile {
    name: string;
    email: string;
    employeeId?: EmployeeId;
}
export type Time = bigint;
export type CycleId = bigint;
export interface UpdateEmployeeProfileArgs {
    status?: EmploymentStatus;
    manager?: string;
    name?: string;
    email?: string;
    jobTitle?: string;
    department?: string;
    principalId?: Principal;
}
export interface OnboardingTask {
    id: TaskId;
    status: TaskStatus;
    title: string;
    dueDate: Time;
    description: string;
    links: string;
    notes: string;
}
export type TaskId = bigint;
export interface EmployeeProfile {
    id: EmployeeId;
    status: EmploymentStatus;
    manager: string;
    name: string;
    createdBy: Principal;
    performanceCycleId?: bigint;
    email: string;
    jobTitle: string;
    department: string;
    onboardingPlanId?: bigint;
    principalId?: Principal;
    startDate: Time;
}
export interface PerformanceReviewCycle {
    id: CycleId;
    status: CycleStatus;
    title: string;
    endDate: Time;
    startDate: Time;
}
export type ReviewId = bigint;
export type EmployeeId = bigint;
export interface CreateEmployeeProfileArgs {
    manager: string;
    name: string;
    email: string;
    jobTitle: string;
    department: string;
    principalId?: Principal;
    startDate: Time;
}
export interface Review {
    id: ReviewId;
    hrReview: string;
    status: ReviewStatus;
    managerReview: string;
    selfReview: string;
    employeeId: EmployeeId;
    cycleId: CycleId;
}
export type GoalId = bigint;
export enum CycleStatus {
    active = "active",
    completed = "completed",
    draft = "draft"
}
export enum EmploymentStatus {
    active = "active",
    terminated = "terminated"
}
export enum GoalStatus {
    notStarted = "notStarted",
    completed = "completed",
    inProgress = "inProgress",
    failed = "failed"
}
export enum ReviewStatus {
    pending = "pending",
    completed = "completed"
}
export enum TaskStatus {
    notStarted = "notStarted",
    done = "done",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addGoals(employeeId: EmployeeId, newGoals: Array<Goal>): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignOnboardingTasks(employeeId: EmployeeId, tasks: Array<OnboardingTask>): Promise<boolean>;
    createEmployee(data: CreateEmployeeProfileArgs): Promise<EmployeeId | null>;
    createPerformanceCycle(cycle: PerformanceReviewCycle): Promise<CycleId>;
    createReview(employeeId: EmployeeId, cycleId: CycleId): Promise<ReviewId>;
    getAllPerformanceCycles(): Promise<Array<PerformanceReviewCycle>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEmployee(id: EmployeeId): Promise<EmployeeProfile | null>;
    getEmployeeGoals(employeeId: EmployeeId): Promise<Array<Goal> | null>;
    getEmployeeReviews(employeeId: EmployeeId): Promise<Array<Review> | null>;
    getMyEmployeeId(): Promise<EmployeeId | null>;
    getOnboardingTasks(employeeId: EmployeeId): Promise<Array<OnboardingTask> | null>;
    getPerformanceCycle(cycleId: CycleId): Promise<PerformanceReviewCycle | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchEmployees(searchTerm: string): Promise<Array<EmployeeProfile>>;
    submitHRReview(employeeId: EmployeeId, reviewId: ReviewId, hrReviewText: string): Promise<boolean>;
    submitManagerReview(employeeId: EmployeeId, reviewId: ReviewId, managerReviewText: string): Promise<boolean>;
    submitSelfReview(employeeId: EmployeeId, reviewId: ReviewId, selfReviewText: string): Promise<boolean>;
    updateEmployee(id: EmployeeId, data: UpdateEmployeeProfileArgs): Promise<boolean>;
    updateGoalProgress(employeeId: EmployeeId, goalId: GoalId, progress: bigint, status: GoalStatus): Promise<boolean>;
    updateOnboardingTaskStatus(employeeId: EmployeeId, taskId: TaskId, newStatus: TaskStatus): Promise<boolean>;
}
import type { CreateEmployeeProfileArgs as _CreateEmployeeProfileArgs, CycleId as _CycleId, CycleStatus as _CycleStatus, EmployeeId as _EmployeeId, EmployeeProfile as _EmployeeProfile, EmploymentStatus as _EmploymentStatus, Goal as _Goal, GoalId as _GoalId, GoalStatus as _GoalStatus, OnboardingTask as _OnboardingTask, PerformanceReviewCycle as _PerformanceReviewCycle, Review as _Review, ReviewId as _ReviewId, ReviewStatus as _ReviewStatus, TaskId as _TaskId, TaskStatus as _TaskStatus, Time as _Time, UpdateEmployeeProfileArgs as _UpdateEmployeeProfileArgs, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addGoals(arg0: EmployeeId, arg1: Array<Goal>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addGoals(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGoals(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignOnboardingTasks(arg0: EmployeeId, arg1: Array<OnboardingTask>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.assignOnboardingTasks(arg0, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignOnboardingTasks(arg0, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEmployee(arg0: CreateEmployeeProfileArgs): Promise<EmployeeId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmployee(to_candid_CreateEmployeeProfileArgs_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmployee(to_candid_CreateEmployeeProfileArgs_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPerformanceCycle(arg0: PerformanceReviewCycle): Promise<CycleId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPerformanceCycle(to_candid_PerformanceReviewCycle_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPerformanceCycle(to_candid_PerformanceReviewCycle_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createReview(arg0: EmployeeId, arg1: CycleId): Promise<ReviewId> {
        if (this.processError) {
            try {
                const result = await this.actor.createReview(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReview(arg0, arg1);
            return result;
        }
    }
    async getAllPerformanceCycles(): Promise<Array<PerformanceReviewCycle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPerformanceCycles();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPerformanceCycles();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployee(arg0: EmployeeId): Promise<EmployeeProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployee(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployee(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployeeGoals(arg0: EmployeeId): Promise<Array<Goal> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeGoals(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeGoals(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployeeReviews(arg0: EmployeeId): Promise<Array<Review> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeReviews(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeReviews(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyEmployeeId(): Promise<EmployeeId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEmployeeId();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEmployeeId();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOnboardingTasks(arg0: EmployeeId): Promise<Array<OnboardingTask> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOnboardingTasks(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOnboardingTasks(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPerformanceCycle(arg0: CycleId): Promise<PerformanceReviewCycle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPerformanceCycle(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPerformanceCycle(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n56(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n56(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchEmployees(arg0: string): Promise<Array<EmployeeProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchEmployees(arg0);
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchEmployees(arg0);
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitHRReview(arg0: EmployeeId, arg1: ReviewId, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitHRReview(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitHRReview(arg0, arg1, arg2);
            return result;
        }
    }
    async submitManagerReview(arg0: EmployeeId, arg1: ReviewId, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitManagerReview(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitManagerReview(arg0, arg1, arg2);
            return result;
        }
    }
    async submitSelfReview(arg0: EmployeeId, arg1: ReviewId, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSelfReview(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSelfReview(arg0, arg1, arg2);
            return result;
        }
    }
    async updateEmployee(arg0: EmployeeId, arg1: UpdateEmployeeProfileArgs): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(arg0, to_candid_UpdateEmployeeProfileArgs_n59(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(arg0, to_candid_UpdateEmployeeProfileArgs_n59(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateGoalProgress(arg0: EmployeeId, arg1: GoalId, arg2: bigint, arg3: GoalStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoalProgress(arg0, arg1, arg2, to_candid_GoalStatus_n4(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoalProgress(arg0, arg1, arg2, to_candid_GoalStatus_n4(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateOnboardingTaskStatus(arg0: EmployeeId, arg1: TaskId, arg2: TaskStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOnboardingTaskStatus(arg0, arg1, to_candid_TaskStatus_n11(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOnboardingTaskStatus(arg0, arg1, to_candid_TaskStatus_n11(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_CycleStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CycleStatus): CycleStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_EmployeeProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeProfile): EmployeeProfile {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_EmploymentStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmploymentStatus): EmploymentStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_GoalStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalStatus): GoalStatus {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Goal_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Goal): Goal {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_OnboardingTask_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OnboardingTask): OnboardingTask {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_PerformanceReviewCycle_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PerformanceReviewCycle): PerformanceReviewCycle {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ReviewStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewStatus): ReviewStatus {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Review_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Review {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmployeeId]): EmployeeId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmployeeProfile]): EmployeeProfile | null {
    return value.length === 0 ? null : from_candid_EmployeeProfile_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Goal>]): Array<Goal> | null {
    return value.length === 0 ? null : from_candid_vec_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Review>]): Array<Review> | null {
    return value.length === 0 ? null : from_candid_vec_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_OnboardingTask>]): Array<OnboardingTask> | null {
    return value.length === 0 ? null : from_candid_vec_n50(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PerformanceReviewCycle]): PerformanceReviewCycle | null {
    return value.length === 0 ? null : from_candid_PerformanceReviewCycle_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CycleId;
    status: _CycleStatus;
    title: string;
    endDate: _Time;
    startDate: _Time;
}): {
    id: CycleId;
    status: CycleStatus;
    title: string;
    endDate: Time;
    startDate: Time;
} {
    return {
        id: value.id,
        status: from_candid_CycleStatus_n23(_uploadFile, _downloadFile, value.status),
        title: value.title,
        endDate: value.endDate,
        startDate: value.startDate
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    employeeId: [] | [_EmployeeId];
}): {
    name: string;
    email: string;
    employeeId?: EmployeeId;
} {
    return {
        name: value.name,
        email: value.email,
        employeeId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.employeeId))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EmployeeId;
    status: _EmploymentStatus;
    manager: string;
    name: string;
    createdBy: Principal;
    performanceCycleId: [] | [bigint];
    email: string;
    jobTitle: string;
    department: string;
    onboardingPlanId: [] | [bigint];
    principalId: [] | [Principal];
    startDate: _Time;
}): {
    id: EmployeeId;
    status: EmploymentStatus;
    manager: string;
    name: string;
    createdBy: Principal;
    performanceCycleId?: bigint;
    email: string;
    jobTitle: string;
    department: string;
    onboardingPlanId?: bigint;
    principalId?: Principal;
    startDate: Time;
} {
    return {
        id: value.id,
        status: from_candid_EmploymentStatus_n33(_uploadFile, _downloadFile, value.status),
        manager: value.manager,
        name: value.name,
        createdBy: value.createdBy,
        performanceCycleId: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.performanceCycleId)),
        email: value.email,
        jobTitle: value.jobTitle,
        department: value.department,
        onboardingPlanId: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.onboardingPlanId)),
        principalId: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.principalId)),
        startDate: value.startDate
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GoalId;
    status: _GoalStatus;
    title: string;
    endDate: _Time;
    description: string;
    progress: bigint;
    startDate: _Time;
}): {
    id: GoalId;
    status: GoalStatus;
    title: string;
    endDate: Time;
    description: string;
    progress: bigint;
    startDate: Time;
} {
    return {
        id: value.id,
        status: from_candid_GoalStatus_n41(_uploadFile, _downloadFile, value.status),
        title: value.title,
        endDate: value.endDate,
        description: value.description,
        progress: value.progress,
        startDate: value.startDate
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReviewId;
    hrReview: string;
    status: _ReviewStatus;
    managerReview: string;
    selfReview: string;
    employeeId: _EmployeeId;
    cycleId: _CycleId;
}): {
    id: ReviewId;
    hrReview: string;
    status: ReviewStatus;
    managerReview: string;
    selfReview: string;
    employeeId: EmployeeId;
    cycleId: CycleId;
} {
    return {
        id: value.id,
        hrReview: value.hrReview,
        status: from_candid_ReviewStatus_n47(_uploadFile, _downloadFile, value.status),
        managerReview: value.managerReview,
        selfReview: value.selfReview,
        employeeId: value.employeeId,
        cycleId: value.cycleId
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    status: _TaskStatus;
    title: string;
    dueDate: _Time;
    description: string;
    links: string;
    notes: string;
}): {
    id: TaskId;
    status: TaskStatus;
    title: string;
    dueDate: Time;
    description: string;
    links: string;
    notes: string;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n53(_uploadFile, _downloadFile, value.status),
        title: value.title,
        dueDate: value.dueDate,
        description: value.description,
        links: value.links,
        notes: value.notes
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
} | {
    draft: null;
}): CycleStatus {
    return "active" in value ? CycleStatus.active : "completed" in value ? CycleStatus.completed : "draft" in value ? CycleStatus.draft : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    terminated: null;
}): EmploymentStatus {
    return "active" in value ? EmploymentStatus.active : "terminated" in value ? EmploymentStatus.terminated : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    failed: null;
}): GoalStatus {
    return "notStarted" in value ? GoalStatus.notStarted : "completed" in value ? GoalStatus.completed : "inProgress" in value ? GoalStatus.inProgress : "failed" in value ? GoalStatus.failed : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
}): ReviewStatus {
    return "pending" in value ? ReviewStatus.pending : "completed" in value ? ReviewStatus.completed : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notStarted: null;
} | {
    done: null;
} | {
    inProgress: null;
}): TaskStatus {
    return "notStarted" in value ? TaskStatus.notStarted : "done" in value ? TaskStatus.done : "inProgress" in value ? TaskStatus.inProgress : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PerformanceReviewCycle>): Array<PerformanceReviewCycle> {
    return value.map((x)=>from_candid_PerformanceReviewCycle_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Goal>): Array<Goal> {
    return value.map((x)=>from_candid_Goal_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Array<Review> {
    return value.map((x)=>from_candid_Review_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OnboardingTask>): Array<OnboardingTask> {
    return value.map((x)=>from_candid_OnboardingTask_n51(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmployeeProfile>): Array<EmployeeProfile> {
    return value.map((x)=>from_candid_EmployeeProfile_n31(_uploadFile, _downloadFile, x));
}
function to_candid_CreateEmployeeProfileArgs_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateEmployeeProfileArgs): _CreateEmployeeProfileArgs {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_CycleStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CycleStatus): _CycleStatus {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_EmploymentStatus_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmploymentStatus): _EmploymentStatus {
    return to_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function to_candid_GoalStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalStatus): _GoalStatus {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_Goal_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): _Goal {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_OnboardingTask_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OnboardingTask): _OnboardingTask {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_PerformanceReviewCycle_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PerformanceReviewCycle): _PerformanceReviewCycle {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateEmployeeProfileArgs_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateEmployeeProfileArgs): _UpdateEmployeeProfileArgs {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: TaskId;
    status: TaskStatus;
    title: string;
    dueDate: Time;
    description: string;
    links: string;
    notes: string;
}): {
    id: _TaskId;
    status: _TaskStatus;
    title: string;
    dueDate: _Time;
    description: string;
    links: string;
    notes: string;
} {
    return {
        id: value.id,
        status: to_candid_TaskStatus_n11(_uploadFile, _downloadFile, value.status),
        title: value.title,
        dueDate: value.dueDate,
        description: value.description,
        links: value.links,
        notes: value.notes
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager: string;
    name: string;
    email: string;
    jobTitle: string;
    department: string;
    principalId?: Principal;
    startDate: Time;
}): {
    manager: string;
    name: string;
    email: string;
    jobTitle: string;
    department: string;
    principalId: [] | [Principal];
    startDate: _Time;
} {
    return {
        manager: value.manager,
        name: value.name,
        email: value.email,
        jobTitle: value.jobTitle,
        department: value.department,
        principalId: value.principalId ? candid_some(value.principalId) : candid_none(),
        startDate: value.startDate
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: CycleId;
    status: CycleStatus;
    title: string;
    endDate: Time;
    startDate: Time;
}): {
    id: _CycleId;
    status: _CycleStatus;
    title: string;
    endDate: _Time;
    startDate: _Time;
} {
    return {
        id: value.id,
        status: to_candid_CycleStatus_n18(_uploadFile, _downloadFile, value.status),
        title: value.title,
        endDate: value.endDate,
        startDate: value.startDate
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: GoalId;
    status: GoalStatus;
    title: string;
    endDate: Time;
    description: string;
    progress: bigint;
    startDate: Time;
}): {
    id: _GoalId;
    status: _GoalStatus;
    title: string;
    endDate: _Time;
    description: string;
    progress: bigint;
    startDate: _Time;
} {
    return {
        id: value.id,
        status: to_candid_GoalStatus_n4(_uploadFile, _downloadFile, value.status),
        title: value.title,
        endDate: value.endDate,
        description: value.description,
        progress: value.progress,
        startDate: value.startDate
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    employeeId?: EmployeeId;
}): {
    name: string;
    email: string;
    employeeId: [] | [_EmployeeId];
} {
    return {
        name: value.name,
        email: value.email,
        employeeId: value.employeeId ? candid_some(value.employeeId) : candid_none()
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: EmploymentStatus;
    manager?: string;
    name?: string;
    email?: string;
    jobTitle?: string;
    department?: string;
    principalId?: Principal;
}): {
    status: [] | [_EmploymentStatus];
    manager: [] | [string];
    name: [] | [string];
    email: [] | [string];
    jobTitle: [] | [string];
    department: [] | [string];
    principalId: [] | [Principal];
} {
    return {
        status: value.status ? candid_some(to_candid_EmploymentStatus_n61(_uploadFile, _downloadFile, value.status)) : candid_none(),
        manager: value.manager ? candid_some(value.manager) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        jobTitle: value.jobTitle ? candid_some(value.jobTitle) : candid_none(),
        department: value.department ? candid_some(value.department) : candid_none(),
        principalId: value.principalId ? candid_some(value.principalId) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    notStarted: null;
} | {
    done: null;
} | {
    inProgress: null;
} {
    return value == TaskStatus.notStarted ? {
        notStarted: null
    } : value == TaskStatus.done ? {
        done: null
    } : value == TaskStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CycleStatus): {
    active: null;
} | {
    completed: null;
} | {
    draft: null;
} {
    return value == CycleStatus.active ? {
        active: null
    } : value == CycleStatus.completed ? {
        completed: null
    } : value == CycleStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalStatus): {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    failed: null;
} {
    return value == GoalStatus.notStarted ? {
        notStarted: null
    } : value == GoalStatus.completed ? {
        completed: null
    } : value == GoalStatus.inProgress ? {
        inProgress: null
    } : value == GoalStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmploymentStatus): {
    active: null;
} | {
    terminated: null;
} {
    return value == EmploymentStatus.active ? {
        active: null
    } : value == EmploymentStatus.terminated ? {
        terminated: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Goal>): Array<_Goal> {
    return value.map((x)=>to_candid_Goal_n2(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<OnboardingTask>): Array<_OnboardingTask> {
    return value.map((x)=>to_candid_OnboardingTask_n9(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
